---
title: "ggplot customization and reading files"
author: "Alicia Canales"
date: "2023-02-09"
output: 
  html_document:
    code_folding: hide
---

YAML header

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

```{r}
library(tidyverse)
library(here)
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)
```

### Read in Excel file, and wrangle data
```{r}
fish_noaa <- readxl::read_excel(here('data', 'foss_landings.xlsx')) %>% 
  janitor::clean_names() %>%# if only using one function in a package then you can use :: with the package and the one function
  mutate(across(where(is.character), tolower)) %>% # across and tolower changes everything to lower case to character columns. applies it to each column
mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>% 
  filter(confidentiality == 'public')


```

#fish plot
```{r}
fish_plot <- ggplot(data = fish_noaa, 
                    aes(x = year, y = pounds, group = nmfs_name)) + 
  geom_line(aes(color = nmfs_name)) +
  theme_minimal()
ggplotly(fish_plot)

### highlight series based on conditions
ggplot(data = fish_noaa, aes(x= year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  gghighlight(max(pounds) > 1e8) + # highlights just the groups that met this criteria
theme_minimal()
```
## Read data from web
```{r}
monroe_wt <- read_csv('https://raw.githubusercontent.com/oharac/esm244_w2023_lab5/master/data/MWTP_Elec_Daily.csv') %>% 
  janitor::clean_names()

monroe_ts <- monroe_wt %>% 
  mutate(date = lubridate::mdy(date)) %>% 
  mutate(record_month = lubridate::month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>%  # made a new column with just the month name
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data = monroe_ts, aes(x = month_name, y = total_kwh)) +
  geom_jitter(aes(color = month_name),
              show.legend = FALSE,
              alpha = 0.5,
              size = .3,
              width = 0.2) +
  theme_classic()
```










